[theme]
base                     = "light"
primaryColor             = "#10B981"
backgroundColor          = "#F2F6F4"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1F2937"
font                     = "sans serif"

[server]
headless = true
